github: ThomasXIONG151215
patreon: # Replace if you have a Patreon account
open_collective: # Replace if you have an OpenCollective
custom: # Replace with your preferred funding link (e.g., PayPal, Ko-fi)
