"""Test that the YAML generated by vfed-web index.html works with Python."""
import yaml
import json
from src.design.project import DesignProject
from src.design.sweep import sweep_design

# Exact YAML from the 609 preset in index.html
YAML_609 = """site:
  lat: 31.0
  lon: 121.5
  year: 2023
  tz_hours: 8
  tilt: 10
  azimuth: 180
envelope:
  U_wall_A: 0.35
  A_window: 0.0
  eta_solar: 0.7
  ach: 0.5
  permeance: 0.0
  rho_air: 1.2
  cp_air: 1005
  V_room: 5000
  C_z: 1200000.0
led:
  auto_deduce: true
  ppfd_target: 200
  efficacy: 2.8
  light_start_hour: 6
  photoperiod_hours: 16
  heat_fraction: 0.8
  covered_area: 100
hvac:
  P_rated_w: 50000
  cop_mode: constant
  cop_value: 3.5
  heat_mode: heat_pump
  P_rated_heat_w: 50000
  deadband_c: 1.0
  min_on_s: 300
  min_off_s: 300
  fan_power_w: 500
  shr_BF: 0.15
  tau_q: 60
  tau_m: 120
deh:
  P_ref_w: 8000
  eta_ref: 1.2
  eta_max: 2.0
  ah_min: 0.004
  ah_ref: 0.01
  deadband_rh: 5.0
  min_on_s: 300
  min_off_s: 300
  fan_power_w: 200
  tau_q: 60
  tau_m: 120
setpoints:
  T_light: 24
  T_dark: 20
  RH: 70
  co2_ppm: 800
  crop_cycle_days: 35
pv:
  eta_pv: 0.20
  area_to_power: 180
  eta_inv: 0.96
  C_pv: 800
  degradation: 0.005
battery:
  c_energy: 150
  c_rate: 0.5
  eta_ch: 0.95
  eta_dis: 0.95
  soc_min: 0.1
  soc_max: 0.9
  cycle_life: 6000
  maintenance: 0.01
tariff:
  hourly_prices: [0.3,0.3,0.3,0.3,0.3,0.3,0.6,0.8,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.8,0.6,0.4,0.3,0.3,0.3]
  export_price: 0.25
equipment_power_w: 2000
interest_rate: 0.05
currency: CNY
exchange_rate: 1.0
space:
  timestep_s: 600
  parameter_ranges: {}
  objective: lcoe
"""

# Test 1: Parse and create DesignProject
print("=" * 60)
print("TEST 1: Parse preset YAML and create DesignProject")
print("=" * 60)
try:
    parsed = yaml.safe_load(YAML_609)
    print(f"  YAML parsed OK, keys: {list(parsed.keys())}")
    print(f"  heat_mode type: {type(parsed['hvac']['heat_mode'])} value: {parsed['hvac']['heat_mode']}")
    project = DesignProject.from_dict(parsed)
    print(f"  SUCCESS: DesignProject created")
    print(f"  hvac.heat_mode = {repr(project.hvac.heat_mode)}")
except Exception as e:
    import traceback
    traceback.print_exc()

# Test 2: Run sweep with ranges
print()
print("=" * 60)
print("TEST 2: Run sweep_design with parameter_ranges")
print("=" * 60)
try:
    project.space.parameter_ranges = {
        "pv_area": [0, 200, 100],
        "battery": [0, 150, 75]
    }
    result = sweep_design(project, cache_dir="weather_cache")
    results_df = result["results"]
    best = result["best"]
    print(f"  SUCCESS: Sweep returned {len(results_df)} results")
    print(f"  Best LCOE: {best['lcoe']}")
    print(f"  Best PV area: {best['pv_area']}")
    print(f"  Best battery: {best['battery_kwh']}")
    print()
    print("  Results keys:", list(results_df.columns))
    print("  First result:", results_df.iloc[0].to_dict())
except Exception as e:
    import traceback
    traceback.print_exc()

# Test 3: Single-point evaluation (no ranges)
print()
print("=" * 60)
print("TEST 3: Single-point evaluation (empty ranges)")
print("=" * 60)
try:
    project.space.parameter_ranges = {}
    result = sweep_design(project, cache_dir="weather_cache")
    print(f"  SUCCESS: Single-point returned")
    print(f"  Results: {result}")
    print(f"  load_kw shape: {result['load'].shape if hasattr(result.get('load'), 'shape') else 'N/A'}")
except Exception as e:
    import traceback
    traceback.print_exc()

# Test 4: Test the yamlStringify function output from index.html
print()
print("=" * 60)
print("TEST 4: Simulate frontend YAML generation")
print("=" * 60)

def flatten_obj(obj, prefix=""):
    out = {}
    for k, v in obj.items():
        path = f"{prefix}.{k}" if prefix else k
        if v and isinstance(v, dict) and not isinstance(v, list):
            out.update(flatten_obj(v, path))
        else:
            out[path] = v
    return out

def deep_set(obj, path, val):
    parts = path.split(".")
    cur = obj
    for i in range(len(parts) - 1):
        if parts[i] not in cur or not isinstance(cur[parts[i]], dict):
            cur[parts[i]] = {}
        cur = cur[parts[i]]
    cur[parts[-1]] = val

def format_yaml_number(n):
    """PyYAML parses scientific notation WITHOUT decimal point as STRING.
    1e-10 -> string; 1.0e-10 -> float. Fix by ensuring decimal point."""
    if not isinstance(n, (int, float)):
        return str(n)
    s = str(n)
    import re
    m = re.match(r'^(-?[\d.]+)[eE](-?\d+)$', s)
    if m:
        mantissa = m.group(1)
        if '.' not in mantissa:
            mantissa += '.0'
        return mantissa + 'e' + m.group(2)
    return s

def yaml_stringify(obj, indent=0):
    pad = "  " * indent
    out = ""
    for k, v in obj.items():
        if v is None:
            continue
        if isinstance(v, list):
            out += f"{pad}{k}:\n"
            if len(v) > 0 and isinstance(v[0], (int, float)):
                out += f"{pad}  [{','.join(format_yaml_number(x) for x in v)}]\n"
            else:
                for item in v:
                    out += f"{pad}  - {item}\n"
        elif isinstance(v, dict):
            out += f"{pad}{k}:\n" + yaml_stringify(v, indent + 1)
        elif isinstance(v, str):
            out += f'{pad}{k}: "{v}"\n'
        else:
            out += f"{pad}{k}: {format_yaml_number(v)}\n"
    return out

# Simulate what index.html does
base_yaml = yaml.safe_load(YAML_609)
form_keys = {
    "site.lat": 31.0, "site.lon": 121.5, "site.tilt": 10, "site.azimuth": 180,
    "site.year": 2023, "site.tz_hours": 8,
    "envelope.V_room": 5000, "envelope.U_wall_A": 0.35, "envelope.A_window": 0.0,
    "envelope.eta_solar": 0.7, "envelope.ach": 0.5, "envelope.permeance": 1e-10,
    "envelope.C_z": 1200000.0,
    "led.ppfd_target": 200, "led.efficacy": 2.8, "led.photoperiod_hours": 16,
    "led.covered_area": 100, "led.heat_fraction": 0.8, "led.light_start_hour": 6,
    "hvac.P_rated_w": 50000, "hvac.cop_value": 3.5, "hvac.P_rated_heat_w": 50000,
    "hvac.deadband_c": 1.0, "hvac.fan_power_w": 500, "hvac.shr_BF": 0.15,
    "hvac.min_on_s": 300, "hvac.min_off_s": 300,
    "deh.P_ref_w": 8000, "deh.eta_ref": 1.2, "deh.ah_min": 0.004,
    "deh.deadband_rh": 5.0, "deh.fan_power_w": 200,
    "setpoints.T_light": 24, "setpoints.T_dark": 20, "setpoints.RH": 70,
    "setpoints.co2_ppm": 800, "setpoints.crop_cycle_days": 35,
    "pv.eta_pv": 0.20, "pv.area_to_power": 180, "pv.C_pv": 800,
    "pv.degradation": 0.005, "pv.eta_inv": 0.96,
    "battery.c_energy": 150, "battery.c_rate": 0.5, "battery.eta_ch": 0.95,
    "battery.eta_dis": 0.95, "battery.cycle_life": 6000, "battery.maintenance": 0.01,
    "interest_rate": 0.05, "equipment_power_w": 2000,
    "tariff.hourly_prices": [0.3]*12 + [0.6, 0.8, 1.0]*3 + [0.8, 0.6, 0.4, 0.3]*2,
    "tariff.export_price": 0.25,
}

# Build YAML like index.html.generateYaml()
obj = json.loads(json.dumps(base_yaml))
skip_keys = {"pv_area"}
for key, val in form_keys.items():
    if key in skip_keys:
        continue
    deep_set(obj, key, val)

obj["tariff"] = obj.get("tariff", {})
obj["tariff"]["hourly_prices"] = form_keys.get("tariff.hourly_prices", [])
obj["tariff"]["export_price"] = form_keys.get("tariff.export_price", 0.25)
obj["space"] = obj.get("space", {})
obj["space"]["timestep_s"] = 600
obj["space"]["parameter_ranges"] = {}
obj["space"]["objective"] = "lcoe"

generated_yaml = yaml_stringify(obj)
print("Generated YAML snippet (first 400 chars):")
print(generated_yaml[:400])
print("...")
print()

# Try to re-parse it
try:
    reparsed = yaml.safe_load(generated_yaml)
    print("Re-parsed OK, keys:", list(reparsed.keys()))
    project2 = DesignProject.from_dict(reparsed)
    print("SUCCESS: Re-parsed YAML creates valid DesignProject")
except Exception as e:
    import traceback
    traceback.print_exc()
    print()
    print("ISSUE DETECTED: The generated YAML failed to parse!")

print()
print("=" * 60)
print("ALL TESTS COMPLETE")
print("=" * 60)
